# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170113_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_list',
            name='email_address',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='email_list',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Cities'),
        ),
    ]
