# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20170118_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_list',
            old_name='location',
            new_name='location_id',
        ),
    ]
