# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20170118_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_List',
            new_name='EmailList',
        ),
    ]
