# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_auto_20170118_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillist',
            old_name='location_id',
            new_name='location',
        ),
    ]
